Added the SOLID principles
zahydo/software_engineering_II_lessons pull request #7
Opened 2023-03-23 02:41 UTC by Jojan-Esteban-Serna

Jojan Esteban Serna Serna

2023-03-23 03:08 UTC, zahydo commented on principles/solid/dependencyInjection.md
> +	private UserRepository userRepository;
Change to an interface, and explain why it's a  better option using interfaces

2023-03-23 03:15 UTC, zahydo requested changes
Fix comments. Good job.

2023-03-23 03:15 UTC, zahydo commented on principles/solid/dependencyInjection.md
> +	private UserRepository userRepository;
The description of all the principles must include the problem, how it solves, and the benefits of applying it.

2023-03-23 04:40 UTC, Jojan-Esteban-Serna commented
I think i'm done

2023-03-25 18:18 UTC, zahydo approved these changes
Good Job.

2023-03-25 18:18 UTC, merged