Add contributing
zahydo/software_engineering_II_lessons pull request #8
Opened 2023-03-23 12:43 UTC by JSarabino

Juan Camilo Sarabino Alegria

2023-03-23 12:49 UTC, zahydo commented on principles/solid/dependencyInjection.md
> +The code will work, for now, but what if we wanted to add another engine type, let’s say a diesel engine?
This is not the right example for Dependency Injection. It's more familiar with Open/Closed

2023-03-23 12:50 UTC, zahydo commented on principles/solid/liskvsustitution.md
> +    public class Rectangle {
Wrong code format. Use ```java to format in Markdown

2023-03-23 12:52 UTC, zahydo requested changes
The descriptions of the principles must include the problem, how it solves, and the benefits. Also, the examples are very simple.

2023-03-23 12:52 UTC, zahydo commented
Change the name of the Pull Request with the name of the branch

2023-03-23 14:41 UTC, JSarabino commented on principles/solid/liskvsustitution.md
> +    public class Rectangle {
i didn't knew the Markdown format, thanks!

2023-03-25 17:40 UTC, zahydo commented
Checked

2023-03-25 17:40 UTC, closed without merging